import { resultsByMatchId } from "@/lib/results";

export type GroupKey =
  | "A"
  | "B"
  | "C"
  | "D"
  | "E"
  | "F"
  | "G"
  | "H"
  | "I"
  | "J"
  | "K"
  | "L";

export type MatchResult = {
  homeScore: number;
  awayScore: number;
};

export type WorldCupMatch = {
  id: string;
  group: GroupKey;
  matchday: number;
  dateLabel: string;
  timeLabel: string;
  homeTeam: string;
  awayTeam: string;
  venue: string;
  result?: MatchResult;
};

export const groupNames: GroupKey[] = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
];

export const matches: WorldCupMatch[] = [
  {
    id: "2026-06-11-mexico-south-africa",
    group: "A",
    matchday: 1,
    dateLabel: "Quinta, 11 de junho",
    timeLabel: "13:00 UTC-6",
    homeTeam: "México",
    awayTeam: "África do Sul",
    venue: "Cidade do México",
    result: { homeScore: 2, awayScore: 0 },
  },
  {
    id: "2026-06-11-south-korea-czech-republic",
    group: "A",
    matchday: 1,
    dateLabel: "Quinta, 11 de junho",
    timeLabel: "20:00 UTC-6",
    homeTeam: "Coreia do Sul",
    awayTeam: "Tchéquia",
    venue: "Guadalajara (Zapopan)",
    result: { homeScore: 2, awayScore: 1 },
  },
  {
    id: "2026-06-18-czech-republic-south-africa",
    group: "A",
    matchday: 8,
    dateLabel: "Quinta, 18 de junho",
    timeLabel: "12:00 UTC-4",
    homeTeam: "Tchéquia",
    awayTeam: "África do Sul",
    venue: "Atlanta",
  },
  {
    id: "2026-06-18-mexico-south-korea",
    group: "A",
    matchday: 8,
    dateLabel: "Quinta, 18 de junho",
    timeLabel: "19:00 UTC-6",
    homeTeam: "México",
    awayTeam: "Coreia do Sul",
    venue: "Guadalajara (Zapopan)",
  },
  {
    id: "2026-06-24-czech-republic-mexico",
    group: "A",
    matchday: 14,
    dateLabel: "Quarta, 24 de junho",
    timeLabel: "19:00 UTC-6",
    homeTeam: "Tchéquia",
    awayTeam: "México",
    venue: "Cidade do México",
  },
  {
    id: "2026-06-24-south-africa-south-korea",
    group: "A",
    matchday: 14,
    dateLabel: "Quarta, 24 de junho",
    timeLabel: "19:00 UTC-6",
    homeTeam: "África do Sul",
    awayTeam: "Coreia do Sul",
    venue: "Monterrey (Guadalupe)",
  },
  {
    id: "2026-06-12-canada-bosnia-herzegovina",
    group: "B",
    matchday: 2,
    dateLabel: "Sexta, 12 de junho",
    timeLabel: "15:00 UTC-4",
    homeTeam: "Canadá",
    awayTeam: "Bósnia e Herzegovina",
    venue: "Toronto",
    result: { homeScore: 1, awayScore: 1 },
  },
  {
    id: "2026-06-13-qatar-switzerland",
    group: "B",
    matchday: 3,
    dateLabel: "Sábado, 13 de junho",
    timeLabel: "12:00 UTC-7",
    homeTeam: "Catar",
    awayTeam: "Suíça",
    venue: "Baía de São Francisco (Santa Clara)",
    result: { homeScore: 1, awayScore: 1 },
  },
  {
    id: "2026-06-18-switzerland-bosnia-herzegovina",
    group: "B",
    matchday: 8,
    dateLabel: "Quinta, 18 de junho",
    timeLabel: "12:00 UTC-7",
    homeTeam: "Suíça",
    awayTeam: "Bósnia e Herzegovina",
    venue: "Los Angeles (Inglewood)",
  },
  {
    id: "2026-06-18-canada-qatar",
    group: "B",
    matchday: 8,
    dateLabel: "Quinta, 18 de junho",
    timeLabel: "15:00 UTC-7",
    homeTeam: "Canadá",
    awayTeam: "Catar",
    venue: "Vancouver",
  },
  {
    id: "2026-06-24-switzerland-canada",
    group: "B",
    matchday: 14,
    dateLabel: "Quarta, 24 de junho",
    timeLabel: "12:00 UTC-7",
    homeTeam: "Suíça",
    awayTeam: "Canadá",
    venue: "Vancouver",
  },
  {
    id: "2026-06-24-bosnia-herzegovina-qatar",
    group: "B",
    matchday: 14,
    dateLabel: "Quarta, 24 de junho",
    timeLabel: "12:00 UTC-7",
    homeTeam: "Bósnia e Herzegovina",
    awayTeam: "Catar",
    venue: "Seattle",
  },
  {
    id: "2026-06-13-brazil-morocco",
    group: "C",
    matchday: 3,
    dateLabel: "Sábado, 13 de junho",
    timeLabel: "18:00 UTC-4",
    homeTeam: "Brasil",
    awayTeam: "Marrocos",
    venue: "Nova York/Nova Jersey (East Rutherford)",
    result: { homeScore: 1, awayScore: 1 },
  },
  {
    id: "2026-06-13-haiti-scotland",
    group: "C",
    matchday: 3,
    dateLabel: "Sábado, 13 de junho",
    timeLabel: "21:00 UTC-4",
    homeTeam: "Haiti",
    awayTeam: "Escócia",
    venue: "Boston (Foxborough)",
    result: { homeScore: 0, awayScore: 1 },
  },
  {
    id: "2026-06-19-scotland-morocco",
    group: "C",
    matchday: 9,
    dateLabel: "Sexta, 19 de junho",
    timeLabel: "18:00 UTC-4",
    homeTeam: "Escócia",
    awayTeam: "Marrocos",
    venue: "Boston (Foxborough)",
  },
  {
    id: "2026-06-19-brazil-haiti",
    group: "C",
    matchday: 9,
    dateLabel: "Sexta, 19 de junho",
    timeLabel: "20:30 UTC-4",
    homeTeam: "Brasil",
    awayTeam: "Haiti",
    venue: "Filadélfia",
  },
  {
    id: "2026-06-24-scotland-brazil",
    group: "C",
    matchday: 14,
    dateLabel: "Quarta, 24 de junho",
    timeLabel: "18:00 UTC-4",
    homeTeam: "Escócia",
    awayTeam: "Brasil",
    venue: "Miami (Miami Gardens)",
  },
  {
    id: "2026-06-24-morocco-haiti",
    group: "C",
    matchday: 14,
    dateLabel: "Quarta, 24 de junho",
    timeLabel: "18:00 UTC-4",
    homeTeam: "Marrocos",
    awayTeam: "Haiti",
    venue: "Atlanta",
  },
  {
    id: "2026-06-12-usa-paraguay",
    group: "D",
    matchday: 2,
    dateLabel: "Sexta, 12 de junho",
    timeLabel: "18:00 UTC-7",
    homeTeam: "Estados Unidos",
    awayTeam: "Paraguai",
    venue: "Los Angeles (Inglewood)",
    result: { homeScore: 4, awayScore: 1 },
  },
  {
    id: "2026-06-13-australia-turkey",
    group: "D",
    matchday: 3,
    dateLabel: "Sábado, 13 de junho",
    timeLabel: "21:00 UTC-7",
    homeTeam: "Austrália",
    awayTeam: "Turquia",
    venue: "Vancouver",
    result: { homeScore: 2, awayScore: 0 },
  },
  {
    id: "2026-06-19-usa-australia",
    group: "D",
    matchday: 9,
    dateLabel: "Sexta, 19 de junho",
    timeLabel: "12:00 UTC-7",
    homeTeam: "Estados Unidos",
    awayTeam: "Austrália",
    venue: "Seattle",
  },
  {
    id: "2026-06-19-turkey-paraguay",
    group: "D",
    matchday: 9,
    dateLabel: "Sexta, 19 de junho",
    timeLabel: "20:00 UTC-7",
    homeTeam: "Turquia",
    awayTeam: "Paraguai",
    venue: "Baía de São Francisco (Santa Clara)",
  },
  {
    id: "2026-06-25-turkey-usa",
    group: "D",
    matchday: 15,
    dateLabel: "Quinta, 25 de junho",
    timeLabel: "19:00 UTC-7",
    homeTeam: "Turquia",
    awayTeam: "Estados Unidos",
    venue: "Los Angeles (Inglewood)",
  },
  {
    id: "2026-06-25-paraguay-australia",
    group: "D",
    matchday: 15,
    dateLabel: "Quinta, 25 de junho",
    timeLabel: "19:00 UTC-7",
    homeTeam: "Paraguai",
    awayTeam: "Austrália",
    venue: "Baía de São Francisco (Santa Clara)",
  },
  {
    id: "2026-06-14-germany-curacao",
    group: "E",
    matchday: 4,
    dateLabel: "Domingo, 14 de junho",
    timeLabel: "12:00 UTC-5",
    homeTeam: "Alemanha",
    awayTeam: "Curaçao",
    venue: "Houston",
    result: { homeScore: 7, awayScore: 1 },
  },
  {
    id: "2026-06-14-ivory-coast-ecuador",
    group: "E",
    matchday: 4,
    dateLabel: "Domingo, 14 de junho",
    timeLabel: "19:00 UTC-4",
    homeTeam: "Costa do Marfim",
    awayTeam: "Equador",
    venue: "Filadélfia",
    result: { homeScore: 1, awayScore: 0 },
  },
  {
    id: "2026-06-20-germany-ivory-coast",
    group: "E",
    matchday: 10,
    dateLabel: "Sábado, 20 de junho",
    timeLabel: "16:00 UTC-4",
    homeTeam: "Alemanha",
    awayTeam: "Costa do Marfim",
    venue: "Toronto",
  },
  {
    id: "2026-06-20-ecuador-curacao",
    group: "E",
    matchday: 10,
    dateLabel: "Sábado, 20 de junho",
    timeLabel: "19:00 UTC-5",
    homeTeam: "Equador",
    awayTeam: "Curaçao",
    venue: "Kansas City",
  },
  {
    id: "2026-06-25-curacao-ivory-coast",
    group: "E",
    matchday: 15,
    dateLabel: "Quinta, 25 de junho",
    timeLabel: "16:00 UTC-4",
    homeTeam: "Curaçao",
    awayTeam: "Costa do Marfim",
    venue: "Filadélfia",
  },
  {
    id: "2026-06-25-ecuador-germany",
    group: "E",
    matchday: 15,
    dateLabel: "Quinta, 25 de junho",
    timeLabel: "16:00 UTC-4",
    homeTeam: "Equador",
    awayTeam: "Alemanha",
    venue: "Nova York/Nova Jersey (East Rutherford)",
  },
  {
    id: "2026-06-14-netherlands-japan",
    group: "F",
    matchday: 4,
    dateLabel: "Domingo, 14 de junho",
    timeLabel: "15:00 UTC-5",
    homeTeam: "Países Baixos",
    awayTeam: "Japão",
    venue: "Dallas (Arlington)",
    result: { homeScore: 2, awayScore: 2 },
  },
  {
    id: "2026-06-14-sweden-tunisia",
    group: "F",
    matchday: 4,
    dateLabel: "Domingo, 14 de junho",
    timeLabel: "20:00 UTC-6",
    homeTeam: "Suécia",
    awayTeam: "Tunísia",
    venue: "Monterrey (Guadalupe)",
    result: { homeScore: 5, awayScore: 1 },
  },
  {
    id: "2026-06-20-netherlands-sweden",
    group: "F",
    matchday: 10,
    dateLabel: "Sábado, 20 de junho",
    timeLabel: "12:00 UTC-5",
    homeTeam: "Países Baixos",
    awayTeam: "Suécia",
    venue: "Houston",
  },
  {
    id: "2026-06-20-tunisia-japan",
    group: "F",
    matchday: 10,
    dateLabel: "Sábado, 20 de junho",
    timeLabel: "22:00 UTC-6",
    homeTeam: "Tunísia",
    awayTeam: "Japão",
    venue: "Monterrey (Guadalupe)",
  },
  {
    id: "2026-06-25-japan-sweden",
    group: "F",
    matchday: 15,
    dateLabel: "Quinta, 25 de junho",
    timeLabel: "18:00 UTC-5",
    homeTeam: "Japão",
    awayTeam: "Suécia",
    venue: "Dallas (Arlington)",
  },
  {
    id: "2026-06-25-tunisia-netherlands",
    group: "F",
    matchday: 15,
    dateLabel: "Quinta, 25 de junho",
    timeLabel: "18:00 UTC-5",
    homeTeam: "Tunísia",
    awayTeam: "Países Baixos",
    venue: "Kansas City",
  },
  {
    id: "2026-06-15-belgium-egypt",
    group: "G",
    matchday: 5,
    dateLabel: "Segunda, 15 de junho",
    timeLabel: "12:00 UTC-7",
    homeTeam: "Bélgica",
    awayTeam: "Egito",
    venue: "Seattle",
    result: { homeScore: 1, awayScore: 1 },
  },
  {
    id: "2026-06-15-iran-new-zealand",
    group: "G",
    matchday: 5,
    dateLabel: "Segunda, 15 de junho",
    timeLabel: "18:00 UTC-7",
    homeTeam: "Irã",
    awayTeam: "Nova Zelândia",
    venue: "Los Angeles (Inglewood)",
  },
  {
    id: "2026-06-21-belgium-iran",
    group: "G",
    matchday: 11,
    dateLabel: "Domingo, 21 de junho",
    timeLabel: "12:00 UTC-7",
    homeTeam: "Bélgica",
    awayTeam: "Irã",
    venue: "Los Angeles (Inglewood)",
  },
  {
    id: "2026-06-21-new-zealand-egypt",
    group: "G",
    matchday: 11,
    dateLabel: "Domingo, 21 de junho",
    timeLabel: "18:00 UTC-7",
    homeTeam: "Nova Zelândia",
    awayTeam: "Egito",
    venue: "Vancouver",
  },
  {
    id: "2026-06-26-egypt-iran",
    group: "G",
    matchday: 16,
    dateLabel: "Sexta, 26 de junho",
    timeLabel: "20:00 UTC-7",
    homeTeam: "Egito",
    awayTeam: "Irã",
    venue: "Seattle",
  },
  {
    id: "2026-06-26-new-zealand-belgium",
    group: "G",
    matchday: 16,
    dateLabel: "Sexta, 26 de junho",
    timeLabel: "20:00 UTC-7",
    homeTeam: "Nova Zelândia",
    awayTeam: "Bélgica",
    venue: "Vancouver",
  },
  {
    id: "2026-06-15-spain-cape-verde",
    group: "H",
    matchday: 5,
    dateLabel: "Segunda, 15 de junho",
    timeLabel: "12:00 UTC-4",
    homeTeam: "Espanha",
    awayTeam: "Cabo Verde",
    venue: "Atlanta",
    result: { homeScore: 0, awayScore: 0 },
  },
  {
    id: "2026-06-15-saudi-arabia-uruguay",
    group: "H",
    matchday: 5,
    dateLabel: "Segunda, 15 de junho",
    timeLabel: "18:00 UTC-4",
    homeTeam: "Arábia Saudita",
    awayTeam: "Uruguai",
    venue: "Miami (Miami Gardens)",
  },
  {
    id: "2026-06-21-spain-saudi-arabia",
    group: "H",
    matchday: 11,
    dateLabel: "Domingo, 21 de junho",
    timeLabel: "12:00 UTC-4",
    homeTeam: "Espanha",
    awayTeam: "Arábia Saudita",
    venue: "Atlanta",
  },
  {
    id: "2026-06-21-uruguay-cape-verde",
    group: "H",
    matchday: 11,
    dateLabel: "Domingo, 21 de junho",
    timeLabel: "18:00 UTC-4",
    homeTeam: "Uruguai",
    awayTeam: "Cabo Verde",
    venue: "Miami (Miami Gardens)",
  },
  {
    id: "2026-06-26-cape-verde-saudi-arabia",
    group: "H",
    matchday: 16,
    dateLabel: "Sexta, 26 de junho",
    timeLabel: "19:00 UTC-5",
    homeTeam: "Cabo Verde",
    awayTeam: "Arábia Saudita",
    venue: "Houston",
  },
  {
    id: "2026-06-26-uruguay-spain",
    group: "H",
    matchday: 16,
    dateLabel: "Sexta, 26 de junho",
    timeLabel: "18:00 UTC-6",
    homeTeam: "Uruguai",
    awayTeam: "Espanha",
    venue: "Guadalajara (Zapopan)",
  },
  {
    id: "2026-06-16-france-senegal",
    group: "I",
    matchday: 6,
    dateLabel: "Terça, 16 de junho",
    timeLabel: "15:00 UTC-4",
    homeTeam: "França",
    awayTeam: "Senegal",
    venue: "Nova York/Nova Jersey (East Rutherford)",
  },
  {
    id: "2026-06-16-iraq-norway",
    group: "I",
    matchday: 6,
    dateLabel: "Terça, 16 de junho",
    timeLabel: "18:00 UTC-4",
    homeTeam: "Iraque",
    awayTeam: "Noruega",
    venue: "Boston (Foxborough)",
  },
  {
    id: "2026-06-22-france-iraq",
    group: "I",
    matchday: 12,
    dateLabel: "Segunda, 22 de junho",
    timeLabel: "17:00 UTC-4",
    homeTeam: "França",
    awayTeam: "Iraque",
    venue: "Filadélfia",
  },
  {
    id: "2026-06-22-norway-senegal",
    group: "I",
    matchday: 12,
    dateLabel: "Segunda, 22 de junho",
    timeLabel: "20:00 UTC-4",
    homeTeam: "Noruega",
    awayTeam: "Senegal",
    venue: "Nova York/Nova Jersey (East Rutherford)",
  },
  {
    id: "2026-06-26-norway-france",
    group: "I",
    matchday: 16,
    dateLabel: "Sexta, 26 de junho",
    timeLabel: "15:00 UTC-4",
    homeTeam: "Noruega",
    awayTeam: "França",
    venue: "Boston (Foxborough)",
  },
  {
    id: "2026-06-26-senegal-iraq",
    group: "I",
    matchday: 16,
    dateLabel: "Sexta, 26 de junho",
    timeLabel: "15:00 UTC-4",
    homeTeam: "Senegal",
    awayTeam: "Iraque",
    venue: "Toronto",
  },
  {
    id: "2026-06-16-argentina-algeria",
    group: "J",
    matchday: 6,
    dateLabel: "Terça, 16 de junho",
    timeLabel: "20:00 UTC-5",
    homeTeam: "Argentina",
    awayTeam: "Argélia",
    venue: "Kansas City",
  },
  {
    id: "2026-06-16-austria-jordan",
    group: "J",
    matchday: 6,
    dateLabel: "Terça, 16 de junho",
    timeLabel: "21:00 UTC-7",
    homeTeam: "Áustria",
    awayTeam: "Jordânia",
    venue: "Baía de São Francisco (Santa Clara)",
  },
  {
    id: "2026-06-22-argentina-austria",
    group: "J",
    matchday: 12,
    dateLabel: "Segunda, 22 de junho",
    timeLabel: "12:00 UTC-5",
    homeTeam: "Argentina",
    awayTeam: "Áustria",
    venue: "Dallas (Arlington)",
  },
  {
    id: "2026-06-22-jordan-algeria",
    group: "J",
    matchday: 12,
    dateLabel: "Segunda, 22 de junho",
    timeLabel: "20:00 UTC-7",
    homeTeam: "Jordânia",
    awayTeam: "Argélia",
    venue: "Baía de São Francisco (Santa Clara)",
  },
  {
    id: "2026-06-27-algeria-austria",
    group: "J",
    matchday: 17,
    dateLabel: "Sábado, 27 de junho",
    timeLabel: "21:00 UTC-5",
    homeTeam: "Argélia",
    awayTeam: "Áustria",
    venue: "Kansas City",
  },
  {
    id: "2026-06-27-jordan-argentina",
    group: "J",
    matchday: 17,
    dateLabel: "Sábado, 27 de junho",
    timeLabel: "21:00 UTC-5",
    homeTeam: "Jordânia",
    awayTeam: "Argentina",
    venue: "Dallas (Arlington)",
  },
  {
    id: "2026-06-17-portugal-dr-congo",
    group: "K",
    matchday: 7,
    dateLabel: "Quarta, 17 de junho",
    timeLabel: "12:00 UTC-5",
    homeTeam: "Portugal",
    awayTeam: "RD Congo",
    venue: "Houston",
  },
  {
    id: "2026-06-17-uzbekistan-colombia",
    group: "K",
    matchday: 7,
    dateLabel: "Quarta, 17 de junho",
    timeLabel: "20:00 UTC-6",
    homeTeam: "Uzbequistão",
    awayTeam: "Colômbia",
    venue: "Cidade do México",
  },
  {
    id: "2026-06-23-portugal-uzbekistan",
    group: "K",
    matchday: 13,
    dateLabel: "Terça, 23 de junho",
    timeLabel: "12:00 UTC-5",
    homeTeam: "Portugal",
    awayTeam: "Uzbequistão",
    venue: "Houston",
  },
  {
    id: "2026-06-23-colombia-dr-congo",
    group: "K",
    matchday: 13,
    dateLabel: "Terça, 23 de junho",
    timeLabel: "20:00 UTC-6",
    homeTeam: "Colômbia",
    awayTeam: "RD Congo",
    venue: "Guadalajara (Zapopan)",
  },
  {
    id: "2026-06-27-colombia-portugal",
    group: "K",
    matchday: 17,
    dateLabel: "Sábado, 27 de junho",
    timeLabel: "19:30 UTC-4",
    homeTeam: "Colômbia",
    awayTeam: "Portugal",
    venue: "Miami (Miami Gardens)",
  },
  {
    id: "2026-06-27-dr-congo-uzbekistan",
    group: "K",
    matchday: 17,
    dateLabel: "Sábado, 27 de junho",
    timeLabel: "19:30 UTC-4",
    homeTeam: "RD Congo",
    awayTeam: "Uzbequistão",
    venue: "Atlanta",
  },
  {
    id: "2026-06-17-england-croatia",
    group: "L",
    matchday: 7,
    dateLabel: "Quarta, 17 de junho",
    timeLabel: "15:00 UTC-5",
    homeTeam: "Inglaterra",
    awayTeam: "Croácia",
    venue: "Dallas (Arlington)",
  },
  {
    id: "2026-06-17-ghana-panama",
    group: "L",
    matchday: 7,
    dateLabel: "Quarta, 17 de junho",
    timeLabel: "19:00 UTC-4",
    homeTeam: "Gana",
    awayTeam: "Panamá",
    venue: "Toronto",
  },
  {
    id: "2026-06-23-england-ghana",
    group: "L",
    matchday: 13,
    dateLabel: "Terça, 23 de junho",
    timeLabel: "16:00 UTC-4",
    homeTeam: "Inglaterra",
    awayTeam: "Gana",
    venue: "Boston (Foxborough)",
  },
  {
    id: "2026-06-23-panama-croatia",
    group: "L",
    matchday: 13,
    dateLabel: "Terça, 23 de junho",
    timeLabel: "19:00 UTC-4",
    homeTeam: "Panamá",
    awayTeam: "Croácia",
    venue: "Toronto",
  },
  {
    id: "2026-06-27-panama-england",
    group: "L",
    matchday: 17,
    dateLabel: "Sábado, 27 de junho",
    timeLabel: "17:00 UTC-4",
    homeTeam: "Panamá",
    awayTeam: "Inglaterra",
    venue: "Nova York/Nova Jersey (East Rutherford)",
  },
  {
    id: "2026-06-27-croatia-ghana",
    group: "L",
    matchday: 17,
    dateLabel: "Sábado, 27 de junho",
    timeLabel: "17:00 UTC-4",
    homeTeam: "Croácia",
    awayTeam: "Gana",
    venue: "Filadélfia",
  },
];

export const matchIds = new Set(matches.map((match) => match.id));

export const matchesWithResults = matches.map((match) => ({
  ...match,
  result: resultsByMatchId.get(match.id),
}));

export const matchesByGroup = groupNames.map((group) => ({
  group,
  matches: matchesWithResults.filter((match) => match.group === group),
}));
